import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Pokemons List',
  description: 'Pokemons List generated by Next.js',
};

export default function PokemonsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <main className="my-8 text-center">{children}</main>;
}
